followed_tournament_organizers:
  cobra:
    - "bagels"  # COBRA TOs to follow

  abr: # ABR NRDB user IDs to follow
    - "49925"   # bagels
    - "49779"   # tjaketheman
    - "10547"   # ClanDaith
