name: Fetch Facebook Data

on:
  schedule:
    - cron: "0 */4 * * *"  # Runs every 4th hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-facebook-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Avoid using the default GitHub token

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install -r scripts/requirements.txt

      - name: Fetch data from Facebook homepage
        run: python3 scripts/fetch_facebook_data.py

      - name: Commit changes if there are updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/facebook_data.json

          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

          git commit -m "Updated Facebook data - $(date '+%Y-%m-%d %H:%M:%S')"
          git push "https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
